<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use DB;

class AreasTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('areas')->insert([
            'id' => 1,
            'display' => 1, 
            'name' => '指定なし',
            'label' => '',
            'book_label' => '',
            'reorder' =>  1,
            'book_reorder' => 1,
            'area_section_id' => 1,
            'city_id' => 1,
            'prefecture_id' => 1,
            'user_id' =>  1,
        ]);
        DB::table('areas')->insert([
            'id' => 2,
            'display' => 1, 
            'name' => '中央',
            'label' => '中央',
            'book_label' => '中央',
            'reorder' =>  1,
            'book_reorder' => 1,
            'area_section_id' => 2,
            'city_id' => 5,
            'prefecture_id' => 2,
            'user_id' =>  1,
        ]);
        DB::table('areas')->insert([
            'id' => 3,
            'display' => 1, 
            'name' => '豊岡',
            'label' => '豊岡',
            'book_label' => '豊岡',
            'reorder' => 2,
            'book_reorder' => 2,
            'area_section_id' => 2,
            'city_id' => 5,
            'prefecture_id' => 2,
            'user_id' => 1,
        ]);
        DB::table('areas')->insert([
            'id' => 4,
            'display' => 1, 
            'name' => '東旭川・千代田',
            'label' => '東旭川・千代田',
            'book_label' => '東旭川・千代田',
            'reorder' => 3,
            'book_reorder' => 3,
            'area_section_id' => 2,
            'city_id' => 5,
            'prefecture_id' => 2,
            'user_id' => 1,
        ]);
        DB::table('areas')->insert([
            'id' => 5,
            'display' => 1, 
            'name' => '東光',
            'label' => '東光',
            'book_label' => '東光',
            'reorder' =>  4,
            'book_reorder' => 4,
            'city_id' => 5,
            'prefecture_id' => 2,
            'user_id' => 1,
        ]);
        DB::table('areas')->insert([
            'id' => 6,
            'display' => 1, 
            'name' => '新旭川・永山南',
            'label' => '新旭川・永山南',
            'book_label' => '新旭川・永山南',
            'reorder' =>  5,
            'book_reorder' => 5,
            'area_section_id' => 2,
            'city_id' => 5,
            'prefecture_id' => 2,
            'user_id' => 1,
        ]);
        DB::table('areas')->insert([
            'id' => 7,
            'display' => 1, 
            'name' => '永山',
            'label' => '永山',
            'book_label' => '永山',
            'reorder' =>  6,
            'book_reorder' => 6,
            'area_section_id' => 2,
            'city_id' => 5,
            'prefecture_id' => 2,
            'user_id' => 1,
        ]);
        DB::table('areas')->insert([
            'id' => 8,
            'display' => 1, 
            'name' => '末広・東鷹栖',
            'label' => '末広・東鷹栖',
            'book_label' => '末広・東鷹栖',
            'reorder' =>  7,
            'book_reorder' => 7,
            'area_section_id' => 2,
            'city_id' => 5,
            'prefecture_id' => 2,
            'user_id' => 1,
        ]);
        DB::table('areas')->insert([
            'id' => 9,
            'display' => 1, 
            'name' => '春光・春光台',
            'label' => '春光・春光台',
            'book_label' => '春光・春光台',
            'reorder' => 9,
            'book_reorder' => 8,
            'city_id' => 5,
            'prefecture_id' => 2,
            'user_id' => 1,
        ]);
        DB::table('areas')->insert([
            'id' => 10,
            'display' => 1, 
            'name' => '北星・旭星',
            'label' => '北星・旭星',
            'book_label' => '北星・旭星',
            'reorder' => 10,
            'book_reorder' => 9,
            'area_section_id' => 2,
            'city_id' => 5,
            'prefecture_id' => 2,
            'user_id' => 1,
        ]);
        DB::table('areas')->insert([
            'id' => 11,
            'display' => 1, 
            'name' => '神居・江丹別',
            'label' => '神居・江丹別',
            'book_label' => '神居・江丹別',
            'book_reorder' => 10,
            'city_id' => 5,
            'reorder' => 11,
            'prefecture_id' => 2,
            'user_id' => 1,
        ]);
        DB::table('areas')->insert([
            'id' => 12,
            'display' => 1, 
            'name' => '神楽・西神楽',
            'label' => '神楽・西神楽',
            'book_label' => '神楽・西神楽',
            'reorder' => 12,
            'book_reorder' => 11,
            'area_section_id' => 2,
            'city_id' => 5,
            'prefecture_id' => 2,
            'user_id' => 1,
        ]);
        DB::table('areas')->insert([
            'id' => 13,
            'display' => 1, 
            'name' => '道北エリア',
            'label' => '道北エリア',
            'book_label' => '道北エリア',
            'reorder' =>  2,
            'book_reorder' => 1,
            'area_section_id' => 3,
            'city_id' => 5,
            'prefecture_id' => 2,
            'user_id' =>  1,
        ]);
        DB::table('areas')->insert([
            'id' => 14,
            'display' => 1, 
            'name' => '中央区',
            'label' => '中央区',
            'book_label' => '中央区',
            'reorder' =>  13,
            'book_reorder' => 1,
            'area_section_id' => 4,
            'city_id' => 2,
            'prefecture_id' => 2,
            'user_id' => 1,
        ]);
        DB::table('areas')->insert([
            'id' => 15,
            'display' => 1, 
            'name' => '北区',
            'label' => '北区',
            'book_label' => '北区',
            'reorder' =>  14,
            'book_reorder' => 1,
            'area_section_id' => 4,
            'city_id' => 2,
            'prefecture_id' => 2,
            'user_id' => 1,
        ]);
        DB::table('areas')->insert([
            'id' => 16,
            'display' => 1, 
            'name' => '東区',
            'label' => '東区',
            'book_label' => '東区',
            'reorder' => 15,
            'book_reorder' => 1,
            'area_section_id' => 4,
            'city_id' => 2,
            'prefecture_id' => 2,
            'user_id' => 1,
        ]);
        DB::table('areas')->insert([
            'id' => 17,
            'display' => 1, 
            'name' => '白石区',
            'label' => '白石区',
            'book_label' => '白石区',
            'reorder' => 1,
            'book_reorder' => 1,
            'area_section_id' => 4,
            'city_id' => 2,
            'prefecture_id' => 2,
            'user_id' => 1,
        ]);
        DB::table('areas')->insert([
            'id' => 18,
            'display' => 1, 
            'name' => '厚別区',
            'label' => '厚別区',
            'book_label' => '厚別区',
            'reorder' => 1,
            'book_reorder' => 1,
            'area_section_id' => 4,
            'city_id' => 2,
            'prefecture_id' => 2,
            'user_id' => 1,
        ]);
        DB::table('areas')->insert([
            'id' => 19,
            'display' => 1, 
            'name' => '豊平区',
            'label' => '豊平区',
            'book_label' => '豊平区',
            'reorder' => 1,
            'book_reorder' => 1,
            'area_section_id' => 4,
            'city_id' => 2,
            'prefecture_id' => 2,
            'user_id' => 1,
        ]);
        DB::table('areas')->insert([
            'id' => 20,
            'display' => 1, 
            'name' => '清田区',
            'label' => '清田区',
            'book_label' => '清田区',
            'reorder' => 1,
            'book_reorder' => 1,
            'area_section_id' => 4,
            'city_id' => 2,
            'prefecture_id' => 2,
            'user_id' => 1,
        ]);
        DB::table('areas')->insert([
            'id' => 21,
            'display' => 1, 
            'name' => '南区',
            'label' => '南区',
            'book_label' => '南区',
            'reorder' => 1,
            'book_reorder' => 1,
            'area_section_id' => 4,
            'city_id' => 2,
            'prefecture_id' => 2,
            'user_id' => 1,
        ]);
        DB::table('areas')->insert([
            'id' => 22,
            'display' => 1, 
            'name' => '西区',
            'label' => '西区',
            'book_label' => '西区',
            'reorder' => 1,
            'book_reorder' => 1,
            'area_section_id' => 4,
            'city_id' => 2,
            'prefecture_id' => 2,
            'user_id' => 1,
        ]);
        DB::table('areas')->insert([
            'id' => 23,
            'display' => 1, 
            'name' => '手稲区',
            'label' => '手稲区',
            'book_label' => '手稲区',
            'reorder' => 1,
            'book_reorder' => 1,
            'area_section_id' => 4,
            'city_id' => 2,
            'prefecture_id' => 2,
            'user_id' => 1,
        ]);
        DB::table('areas')->insert([
            'id' => 24,
            'display' => 1, 
            'name' => '江別市',
            'label' => '江別市',
            'book_label' => '江別市',
            'reorder' => 1,
            'book_reorder' => 1,
            'area_section_id' => 5,
            'city_id' => 3,
            'prefecture_id' => 2,
            'user_id' => 1,
        ]);
        DB::table('areas')->insert([
            'id' => 25,
            'display' => 1, 
            'name' => '千歳市',
            'label' => '千歳市',
            'book_label' => '千歳市',
            'reorder' => 1,
            'book_reorder' => 2,
            'area_section_id' => 5,
            'city_id' => 3,
            'prefecture_id' => 2,
            'user_id' => 1,
        ]);
        DB::table('areas')->insert([
            'id' => 26,
            'display' => 1, 
            'name' => '恵庭市',
            'label' => '恵庭市',
            'book_label' => '恵庭市',
            'reorder' => 1,
            'book_reorder' => 3,
            'area_section_id' => 5,
            'city_id' => 3,
            'prefecture_id' => 2,
            'user_id' => 1,
        ]);
        DB::table('areas')->insert([
            'id' => 27,
            'display' => 1, 
            'name' => '北広島市',
            'label' => '北広島市',
            'book_label' => '北広島市',
            'reorder' => 1,
            'book_reorder' => 4,
            'area_section_id' => 5,
            'city_id' => 3,
            'prefecture_id' => 2,
            'user_id' => 1,
        ]);
        DB::table('areas')->insert([
            'id' => 28,
            'display' => 1, 
            'name' => '石狩市',
            'label' => '石狩市',
            'book_label' => '石狩市',
            'reorder' => 1,
            'book_reorder' => 5,
            'area_section_id' => 5,
            'city_id' => 3,
            'prefecture_id' => 2,
            'user_id' => 1,
        ]);
        DB::table('areas')->insert([
            'id' => 29,
            'display' => 1, 
            'name' => '石狩郡',
            'label' => '石狩郡',
            'book_label' => '石狩郡',
            'reorder' => 1,
            'book_reorder' => 6,
            'area_section_id' => 5,
            'city_id' => 3,
            'prefecture_id' => 2,
            'user_id' => 1,
        ]);
        DB::table('areas')->insert([
            'id' => 30,
            'display' => 1, 
            'name' => '岩見沢市',
            'label' => '岩見沢市',
            'book_label' => '岩見沢市',
            'reorder' => 1,
            'book_reorder' => 7,
            'area_section_id' => 5,
            'city_id' => 3,
            'prefecture_id' => 2,
            'user_id' => 1,
        ]);
        DB::table('areas')->insert([
            'id' => 31,
            'display' => 1, 
            'name' => '南空知エリア',
            'label' => '南空知エリア',
            'book_label' => '南空知エリア',
            'area_section_id' => 5,
            'reorder' => 1,
            'book_reorder' => 8,
            'city_id' => 3,
        ]);
        DB::table('areas')->insert([
            'id' => 32,
            'display' => 1, 
            'name' => '北空知エリア',
            'label' => '北空知エリア',
            'book_label' => '北空知エリア',
            'reorder' => 1,
            'book_reorder' => 9,
            'area_section_id' => 5,
            'city_id' => 3,
            'prefecture_id' => 2,
            'user_id' => 1,
        ]);
        DB::table('areas')->insert([
            'id' => 33,
            'display' => 1, 
            'name' => 'オホーツクエリア',
            'label' => 'オホーツクエリア',
            'book_label' => 'オホーツクエリア',
            'reorder' => 1,
            'book_reorder' => 1,
            'area_section_id' => 6,
            'city_id' => 3,
            'prefecture_id' => 2,
            'user_id' => 1,
        ]);
        DB::table('areas')->insert([
            'id' => 34,
            'display' => 1, 
            'name' => '根室・釧路エリア',
            'label' => '根室・釧路エリア',
            'book_label' => '根室・釧路エリア',
            'reorder' => 1,
            'book_reorder' => 2,
            'area_section_id' => 6,
            'city_id' => 3,
            'prefecture_id' => 2,
            'user_id' => 1,
        ]);
        DB::table('areas')->insert([
            'id' => 35,
            'display' => 1, 
            'name' => '十勝・日高エリア',
            'label' => '十勝・日高エリア',
            'book_label' => '十勝・日高エリア',
            'reorder' => 1,
            'book_reorder' => 3,
            'area_section_id' => 6,
            'city_id' => 3,
            'prefecture_id' => 2,
            'user_id' => 1,
        ]);
        DB::table('areas')->insert([
            'id' => 36,
            'display' => 1, 
            'name' => '胆振エリア',
            'label' => '胆振エリア',
            'book_label' => '胆振エリア',
            'reorder' => 1,
            'book_reorder' => 1,
            'area_section_id' => 7,
            'city_id' => 3,
            'prefecture_id' => 2,
            'user_id' => 1,
        ]);
        DB::table('areas')->insert([
            'id' => 37,
            'display' => 1, 
            'name' => '後志エリア',
            'label' => '後志エリア',
            'book_label' => '後志エリア',
            'reorder' => 1,
            'book_reorder' => 2,
            'area_section_id' => 7,
            'city_id' => 3,
            'prefecture_id' => 2,
            'user_id' => 1,
        ]);
        DB::table('areas')->insert([
            'id' => 38,
            'display' => 1, 
            'name' => '檜山・渡島エリア',
            'label' => '檜山・渡島エリア',
            'book_label' => '檜山・渡島エリア',
            'reorder' => 1,
            'book_reorder' => 3,
            'area_section_id' => 7,
            'city_id' => 3,
            'prefecture_id' => 2,
            'user_id' => 1,
        ]);
    }
}

