version: '3'
services:
  web:
    container_name: web
    image: nginx
    volumes:
      - ./:/var/www/html
      - ./system/local/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 11061:80
    working_dir: /var/www/html/
    depends_on:
      - php
      - db
      - dbtest
    environment:
      - SERVER_NAME=localhost
    networks:
      - local

  php:
    container_name: php
    build: ./system/local/docker/php
    volumes:
      - ./:/var/www/html/
    networks:
      - local

  db:
    container_name: db
    image: mariadb
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin --innodb-large-prefix=true --innodb-file-format=Barracuda
    volumes:
      # ディレクトリ共有
      - ./:/usr/local/src
      # 初期データを投入するSQLが格納されているdir
      - ./system/local/db/mysql_init:/docker-entrypoint-initdb.d
      # 永続化するときにマウントするdir
      - ./system/local/db/mysql_data:/var/lib/mysql
      # 設定ファイル
      - ./system/local/db/conf.d:/etc/mysql/conf.d
    environment:
      MYSQL_DATABASE: primary
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_USER: root
    networks:
      - local

  dbtest:
    container_name: dbtest
    image: mariadb
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin --innodb-large-prefix=true --innodb-file-format=Barracuda
    volumes:
      # ディレクトリ共有
      - ./:/usr/local/src
      # 初期データを投入するSQLが格納されているdir
      - ./system/local/db/testt_mysql_init:/docker-entrypoint-initdb.d
      # 永続化するときにマウントするdir
      - ./system/local/db/test_mysql_data:/var/lib/mysql
      # 設定ファイル
      - ./system/local/db/test_conf.d:/etc/mysql/conf.d
    environment:
      MYSQL_DATABASE: test_primary
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_USER: root
    networks:
      - local

  selenium:
    container_name: selenium
    image: seleniarm/standalone-chromium
    ports:
      - 11064:4444
      - 11065:5900
    depends_on:
      - web
    links:
      - web
    networks:
      - local
    privileged: true

  phpmyadmin:
    container_name: phpmyadmin
    image: arm64v8/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=
    links:
      - db
    ports:
      - 11066:80
    volumes:
      - ./system/local/phpmyadmin/sessions:/sessions
    networks:
      - local

  phpmyadmintest:
    container_name: phpmyadmintest
    image: arm64v8/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=dbtest
      - PMA_USER=root
      - PMA_PASSWORD=
    links:
      - dbtest
    ports:
      - 11067:80
    volumes:
      - ./system/local/phpmyadmin/sessions:/sessions
    networks:
      - local

networks:
  local: