name: 本番環境バックアップ

on:
  push:
    branches:
      - backup

  #schedule:
    # 定期実行する時間
  #  - cron: '0 22 * * *'      

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: 下準備
        run: mkdir -p ~/.ssh

      - name: docker-compose準備・起動
        run: |
          rm docker-compose.yml
          cp system/docker/backup/x86/docker-compose.yml ./
          docker-compose up -d

      - name: composerインストール（backup用のcomposer.jsonに切り替えて実行）
        run: |
          rm composer.json
          cp system/docker/backup/composer.json ./
          docker-compose exec -T php sh -c "composer install"

      - name: "Prepare SSH key and known hosts"
        run: |
          echo "${{ secrets.SSH_KEY_PRODUCTION }}" > ~/.ssh/secretkey
          chmod 600 ~/.ssh/secretkey
          ssh-keyscan ${{ secrets.SSH_HOST_PRODUCTION }} >> ~/.ssh/known_hosts
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY_PRODUCTION }}

      #- name: Setup tmate session -y
      #  uses: mxschmitt/action-tmate@v1

      - name: deployerのファイルを配置
        run: |
          cp system/deployer/backup.php ./deploy.php

      - name: バックアップを行う（deployer7系／deploy.php）
        run: ./vendor/bin/dep backup -vvvv

