name: ステージングサーバへのデプロイ

on:
  push:
    branches:
      - develop

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: 下準備
        run: |
          mkdir -p ~/.ssh
          cp system/ci/spots storage/app/photos/spots
          ln -s storage/app/photos public/photos

      - name: docker-compose準備・起動
        run: |
          rm docker-compose.yml
          cp system/docker/ci/x86/docker-compose.yml ./
          docker-compose up -d

      - name: キャッシュディレクトリ設定
        run: |
          mkdir bootstrap/cache
          chmod -R 707 bootstrap/cache
          chmod -R 707 storage

      - name: CI実行用のenvファイル設定
        run: |
          cp system/ci/env ./.env
          cp system/ci/env.dusk ./.env.dusk
          cp system/ci/env.testing ./.env.testing

      - name: composerインストール
        run: docker-compose exec -T php sh -c "composer install"

      - name: ステージングサーバーにSSH接続するためのkeyとknown_hostsの設定
        run: |
          echo "${{ secrets.SSH_KEY_STAGING }}" > ~/.ssh/secretkey
          chmod 600 ~/.ssh/secretkey
          ssh-keyscan ${{ secrets.SSH_HOST_STAGING }} >> ~/.ssh/known_hosts
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY_STAGING }}

      - name: deployerのファイルを配置
        run: |
          cp system/deployer/deploy.php ./deploy.php

      #- name: デバッグ時にCI内にSSH接続する（通常は使用しないのでコメントアウトすること）
      #  uses: mxschmitt/action-tmate@v1

      - name: WEBアプリのユニットテスト・結合テストを行う (PHPUnit)
        run: |
          docker-compose exec -T php ./vendor/bin/phpunit -c packages/Tool/Admin/tests/
          docker-compose exec -T php ./vendor/bin/phpunit -c packages/Tool/General/tests/
          docker-compose exec -T php ./vendor/bin/phpunit -c packages/Tool/User/tests/

      - name: WEBアプリのE2Eテストを行う (Laravel Dusk)
        run: |
           docker-compose exec -T php php artisan dusk packages/Tool/Admin/tests/
           docker-compose exec -T php php artisan dusk packages/Tool/General/tests/
           docker-compose exec -T php php artisan dusk packages/Tool/User/tests/

      - name: デプロイを行う（deployer7系／deploy.php）
        run: ./vendor/bin/dep deploy staging -vvvv

