name: mainビルド

on:
  push:
    branches:
      - main

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: 下準備
        run: mkdir -p ~/.ssh

      - name: docker-compose準備・起動
        run: |
          rm docker-compose.yml
          cp system/docker/x86/docker-compose.yml ./
          docker-compose up -d

      - name: キャッシュディレクトリ設定
        run: |
          mkdir bootstrap/cache
          chmod -R 707 bootstrap/cache
          chmod -R 707 storage

      - name: envファイル設定
        run: |
          cp system/ci/env ./.env
          cp system/ci/env.dusk ./.env.dusk

      - name: composerインストール
        run: docker-compose exec -T php sh -c "composer install"

      # WEBアプリのユニットテストを行う
      #- name: apps Unit testing (PHPUnit)
      #  run: |
      #    docker-compose exec -T php ./vendor/bin/phpunit

      # WEBアプリのE2Eテストを行う
      #- name: apps E2E testing (Laravel Dusk)
      #  run: |
      #     docker-compose exec -T php php artisan dusk

      #- name: Setup tmate session -y
      #  uses: mxschmitt/action-tmate@v1
